import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const mount=document.querySelector('#world-canvas'),stage=document.querySelector('#map-stage'),status=document.querySelector('#status'),needle=document.querySelector('.compass img');mount.style.width='100%';mount.style.height='100%';mount.style.left='0';stage.style.top='0';stage.style.bottom='0';
const dateLabel=document.querySelector('#date-label'),timeLabel=document.querySelector('#time-label');function updateClock(){const now=new Date(),months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],hour=now.getHours();dateLabel.textContent=`${months[now.getMonth()]} ${String(now.getDate()).padStart(2,'0')}`;timeLabel.textContent=`${String(hour).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;document.documentElement.dataset.timeOfDay=hour>=18||hour<5?'night':'day'}updateClock();setInterval(updateClock,1000);
const scene=new THREE.Scene(),world=new THREE.Group(),city=new THREE.Group();scene.fog=new THREE.Fog(0xcfeeff,24,76);scene.add(world);world.add(city);stage.style.background='radial-gradient(ellipse 120% 20% at 50% 48%, rgba(249,255,252,.9) 0%, rgba(232,250,245,.48) 42%, transparent 78%), linear-gradient(180deg, #92d6ff 0%, #bfeaff 31%, #ddf6ef 52%, #DAEEDF 74%, #DAEEDF 100%)';
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.domElement.style.cssText='width:100%;height:100%;display:block;';mount.append(renderer.domElement);
const camera=new THREE.OrthographicCamera(-12,12,12,-12,.1,100);camera.position.set(15,17,16);camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x9dd5c1,2.1));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(10,18,8);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(400,400),new THREE.MeshStandardMaterial({color:0xdaeedf,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);
const grassGeometry=new THREE.BoxGeometry(.13,.22,.13),grassMaterial=new THREE.MeshStandardMaterial({color:0xa9d38d,roughness:1});for(let i=0;i<760;i+=1){const tuft=new THREE.Mesh(grassGeometry,grassMaterial),x=((i*37)%381)-190,z=((i*71)%381)-190;tuft.position.set(x,.11,z);world.add(tuft);}
const mats={grass:new THREE.MeshStandardMaterial({color:0x82cf78,roughness:.9}),grassSide:new THREE.MeshStandardMaterial({color:0x5aa56b}),water:new THREE.MeshStandardMaterial({color:0x42cce2,roughness:.35,metalness:.05}),road:new THREE.MeshStandardMaterial({color:0xfff3cf}),wood:new THREE.MeshStandardMaterial({color:0x805238}),leaf:new THREE.MeshStandardMaterial({color:0x358d62}),stone:new THREE.MeshStandardMaterial({color:0xe8e3d6}),roof:new THREE.MeshStandardMaterial({color:0xe0a06d}),mint:new THREE.MeshStandardMaterial({color:0x78e5bf,emissive:0x1d8c69,emissiveIntensity:.35})};
function box(x,y,z,w,h,d,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y+h/2,z);m.castShadow=m.receiveShadow=true;city.add(m);return m}
let route=[[-5.1,5.1],[-4.55,4.65],[-3.9,4.12],[-3.25,3.58],[-2.55,3.08],[-1.85,2.62],[-1.1,2.05],[-.42,1.32],[.28,.63],[1.02,.05],[1.8,-.55],[2.62,-1.05],[3.34,-1.7],[4.08,-2.33]];function roadSegment(a,b){const dx=b[0]-a[0],dz=b[1]-a[1],piece=box((a[0]+b[0])/2,.03,(a[1]+b[1])/2,.56,.06,Math.hypot(dx,dz)+.24,mats.road);piece.rotation.y=Math.atan2(dx,dz)}
function tree(x,z){if(!treeAsset){box(x,.18,z,.22,.8,.22,mats.wood);box(x,.9,z,.85,.85,.85,mats.leaf);box(x,.9,z,.45,1.25,.45,mats.leaf);return}const holder=new THREE.Group(),model=treeAsset.clone(true);model.scale.setScalar(treeScale);model.position.y=treeLift;model.traverse(node=>{if(node.isMesh){node.castShadow=true;node.receiveShadow=true}});holder.add(model);holder.position.set(x,0,z);city.add(holder)}
function simpleHouse(x,z){box(x,.18,z,1.05,.8,.9,mats.stone);box(x,.98,z,1.24,.34,1.08,mats.roof);box(x,.5,z-.47,.15,.28,.05,mats.mint)}
function tower(x,z){box(x,.18,z,.8,2.4,.8,mats.stone);box(x,2.58,z,1.08,.34,1.08,mats.grass);box(x,1.35,z-.43,.12,.8,.04,mats.mint)}
function dragon(){const d=new THREE.Group();[[0,0,0],[.28,.08,0],[.56,.16,0],[-.28,.08,0],[-.55,.22,0],[.15,.32,.25],[-.1,.28,-.25]].forEach(([x,y,z])=>{const m=new THREE.Mesh(new THREE.BoxGeometry(.25,.18,.25),mats.leaf);m.position.set(x,y,z);d.add(m)});d.position.set(1.5,5,-4);city.add(d)}
let houseAsset,houseScale=1,houseLift=0,treeAsset,treeScale=1,treeLift=0,lastProgress=-1;function house(x,z){if(!houseAsset){simpleHouse(x,z);return;}const holder=new THREE.Group(),model=houseAsset.clone(true);model.scale.setScalar(houseScale);model.position.y=houseLift;model.traverse(node=>{if(node.isMesh){node.castShadow=true;node.receiveShadow=true;}});holder.add(model);holder.position.set(x,0,z);holder.rotation.y=Math.PI/2;city.add(holder)}
new GLTFLoader().load('./house-01.glb',gltf=>{houseAsset=gltf.scene;const bounds=new THREE.Box3().setFromObject(houseAsset),size=bounds.getSize(new THREE.Vector3());houseScale=1.25/Math.max(size.x,size.z);houseLift=-bounds.min.y*houseScale;build(lastProgress);render()},undefined,()=>{status.textContent='家モデルを読み込めませんでした'});
new GLTFLoader().load('./tree-01.glb',gltf=>{treeAsset=gltf.scene;const bounds=new THREE.Box3().setFromObject(treeAsset),size=bounds.getSize(new THREE.Vector3());treeScale=1.7/Math.max(size.x,size.z,size.y);treeLift=-bounds.min.y*treeScale;build(lastProgress);render()},undefined,()=>{status.textContent='木モデルを読み込めませんでした'});
function build(progress=0){lastProgress=progress;city.clear();const area=Math.min(route.length-1,Math.floor(progress));if(area<0)return;for(let i=0;i<=area;i+=1){const point=route[i];if(i===0)box(point[0],.03,point[1],.56,.06,.56,mats.road);else roadSegment(route[i-1],point);if(i%3===0)box(point[0],.09,point[1],.18,.15,.18,mats.mint)}if(area>=2){tree(-4.25,3.25)}if(area>=3){box(-2.7,.01,2.25,2.35,.05,1.65,mats.water);tree(-2.2,3.55)}if(area>=5){house(-1.65,3.25);tree(-.9,2.85)}if(area>=7){house(-.25,2.0);tree(.2,1.55)}if(area>=9){tower(1.55,.82);house(1.6,-.1)}if(area>=11){tree(2.8,-.4);house(3.12,-.78)}if(area>=13){tower(4.05,-1.45);dragon()}const[x,z]=route[area],pin=new THREE.Mesh(new THREE.SphereGeometry(.22,16,12),new THREE.MeshStandardMaterial({color:0xffffff,emissive:0x4adba1,emissiveIntensity:.9}));pin.position.set(x,.35,z);city.add(pin)}
let viewSize=16;function resize(){const w=mount.clientWidth,h=mount.clientHeight||1,a=w/h;camera.left=-viewSize*a;camera.right=viewSize*a;camera.top=viewSize;camera.bottom=-viewSize;camera.updateProjectionMatrix();renderer.setSize(w,h,false);renderer.render(scene,camera)}new ResizeObserver(resize).observe(mount);resize();
let yaw=0,down,gesture;const pointers=new Map();const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),mid=(a,b)=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});function render(){world.rotation.y=yaw;needle.style.transform=`rotate(${yaw*180/Math.PI}deg)`;renderer.render(scene,camera)}function startGesture(){const[a,b]=[...pointers.values()],m=mid(a,b);gesture={distance:dist(a,b),mid:m,view:viewSize,x:world.position.x,z:world.position.z};}stage.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});stage.setPointerCapture(e.pointerId);if(pointers.size===1)down={x:e.clientX,y:e.clientY,yaw};if(pointers.size===2){down=null;startGesture();}});stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&down){yaw=down.yaw+(e.clientX-down.x)*.012;camera.position.y=Math.max(11,Math.min(23,17-(e.clientY-down.y)*.04));camera.lookAt(0,0,0);render();return;}if(pointers.size===2&&gesture){const[a,b]=[...pointers.values()],m=mid(a,b);viewSize=Math.max(8,Math.min(30,gesture.view*gesture.distance/dist(a,b)));world.position.x=gesture.x+(m.x-gesture.mid.x)*.025;world.position.z=gesture.z+(m.y-gesture.mid.y)*.025;resize();render();}});function endPointer(e){pointers.delete(e.pointerId);if(pointers.size===1){const p=[...pointers.values()][0];down={x:p.x,y:p.y,yaw};}else down=null;gesture=null;}stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);document.querySelector('#compass').onclick=()=>{yaw=0;viewSize=16;world.position.set(0,0,0);camera.position.set(15,17,16);camera.lookAt(0,0,0);resize();render()};
let watchId=null,walk=null;const walkStore='my-world-walks-v1',distance=(a,b)=>{const r=Math.PI/180,lat=(b.lat-a.lat)*r,lng=(b.lng-a.lng)*r,s=Math.sin(lat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(lng/2)**2;return 12742000*Math.atan2(Math.sqrt(s),Math.sqrt(1-s))},walkDistance=points=>points.slice(1).reduce((total,point,index)=>total+distance(points[index],point),0),formatDistance=meters=>meters<1000?`${Math.round(meters)} m`:`${(meters/1000).toFixed(2)} km`,mapTrack=points=>{if(!points.length)return[];const first=points[0],raw=points.map(point=>[(point.lng-first.lng)*111320*Math.cos(first.lat*Math.PI/180),-(point.lat-first.lat)*111320]),xs=raw.map(point=>point[0]),zs=raw.map(point=>point[1]),span=Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...zs)-Math.min(...zs),1),scale=12/span,cx=(Math.max(...xs)+Math.min(...xs))/2,cz=(Math.max(...zs)+Math.min(...zs))/2;return raw.map(point=>[(point[0]-cx)*scale,(point[1]-cz)*scale])},saveWalk=record=>{const walks=JSON.parse(localStorage.getItem(walkStore)||'[]');walks.unshift({...record,endedAt:Date.now(),distance:walkDistance(record.points)});localStorage.setItem(walkStore,JSON.stringify(walks.slice(0,20)))},showWalk=points=>{route=mapTrack(points);if(route.length)build(route.length-1)},stopWalk=()=>{if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;if(walk?.points.length){saveWalk(walk);showWalk(walk.points);status.textContent=`保存しました · ${formatDistance(walkDistance(walk.points))}`}walk=null;document.querySelector('#replay').setAttribute('aria-label','GPS記録を開始')},startWalk=()=>{if(!navigator.geolocation){status.textContent='この端末ではGPSを使えません';return}walk={startedAt:Date.now(),points:[]};status.textContent='位置情報を確認しています...';watchId=navigator.geolocation.watchPosition(position=>{const point={lat:position.coords.latitude,lng:position.coords.longitude,accuracy:position.coords.accuracy,altitude:Number.isFinite(position.coords.altitude)?position.coords.altitude:null,altitudeAccuracy:Number.isFinite(position.coords.altitudeAccuracy)?position.coords.altitudeAccuracy:null,time:position.timestamp},last=walk.points.at(-1);if(point.accuracy>80||(last&&distance(last,point)<7))return;walk.points.push(point);showWalk(walk.points);status.textContent=`記録中 · ${formatDistance(walkDistance(walk.points))}`},error=>{status.textContent=error.code===1?'位置情報を許可してください':'GPSを取得できません';stopWalk()},{enableHighAccuracy:true,maximumAge:3000,timeout:15000});document.querySelector('#replay').setAttribute('aria-label','GPS記録を停止')};document.querySelector('#replay').onclick=()=>watchId===null?startWalk():stopWalk();const latestWalk=JSON.parse(localStorage.getItem(walkStore)||'[]')[0];if(latestWalk?.points?.length>1){showWalk(latestWalk.points);status.textContent=`前回の散歩 · ${formatDistance(latestWalk.distance||walkDistance(latestWalk.points))}`}else build(-1);render();
const panels={memories:document.querySelector('#memories'),history:document.querySelector('#history')};function show(n){Object.entries(panels).forEach(([k,v])=>v.classList.toggle('open',k===n));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.panel===(n||'map')));if(n==='history')document.querySelector('#history-list').innerHTML='<article class="history-item"><div class="history-icon">✦</div><div><p>川沿いの空がきれいだった。</p><time>2026/09/08 10:03</time></div></article>'}document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.panel==='map'?null:b.dataset.panel));document.querySelectorAll('.close').forEach(b=>b.onclick=()=>show(null));document.querySelector('#save').onclick=()=>show('history');
function centerCity(){city.position.set(0,0,0);const bounds=new THREE.Box3().setFromObject(city);if(bounds.isEmpty())return;const center=bounds.getCenter(new THREE.Vector3());city.position.set(-center.x,0,-center.z)}const rawBuild=build;build=value=>{rawBuild(value);centerCity()};centerCity();render();
